#!/usr/bin/env ruby


require 'trollop'

$:.unshift File.dirname(File.expand_path($0)) # put path of this script on require path
require 'update_utils'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
   banner File.basename($0)
   opt :input, "taxonomy to check", :type=>:string, :required=>true
end

check_taxonomic_consistency(opts.input)
