#!/usr/bin/env ruby


require 'trollop'
require 'digest/sha1'
require 'mysql'
require 'open-uri'
require 'net/ftp'
require 'csv'

$VERBOSE=nil

$:.unshift File.dirname(File.expand_path($0)) # put path of this script on require path
require 'update_utils'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
   banner File.basename($0)
   opt :host, "phylodb database host", :type=>:string, :required=>true
   opt :categories, "categories to pick from", :type=>:strings, :default=> ["Bacteria", "Fungi", "Viruses", "Protozoa"]
end


db = Mysql.new(opts.host, "access", "access", "phylodb")

taxids = Hash.new
db.query("SELECT distinct taxon_id FROM contigs").each do |row|
   taxids[row.first.to_i] = true
end


taxonomy = Hash.new
contigs = Hash.new
Net::FTP.open("ftp.ncbi.nih.gov") do |ftp|
   ftp.login
   opts.categories.each do |type|
      STDERR << "Looking at genomes from " << type << "...\n"
      ftp.chdir("/genomes/#{type}")
      count = 0
      ftp.list("*/*.rpt").each do |rpt|
         ftp.getbinaryfile(rpt.split(" ").last, "rpt.txt", 1024)
         acc = nil
         tid = nil
         File.new("rpt.txt").each do |line|
            if line =~/Accession: ([^\n]*)\n/
               acc = $1
            elsif line =~/Taxid: ([^\n]*)\n/
               tid = $1.to_i
               if !taxids[tid]
                  taxonomy[tid] = recurseTaxonomy(db, tid) if !taxonomy[tid]
                  contigs[tid] = [] if !contigs[tid]
                  contigs[tid].push(acc)
               end
            end
         end
         count += 1
         if count % 100 == 0
            STDERR << "Processing genome " << count << "...\n"
         end
      end
   end
end

db.close

STDERR << "Writing Spreadsheet...\n"
out = File.new("ncbi_new.csv", "w")
out.print ["Taxon Id", "Species", "Taxonomy", "Accs"].to_csv
taxonomy.keys.sort.each do |tid|
   next if taxonomy[tid].last.nil?
   out.print [tid, taxonomy[tid].last, taxonomy[tid].join("; "), contigs[tid].join(" ")].to_csv
end

out.close
