#!/usr/bin/env ruby


require 'trollop'
require 'mysql'

$:.unshift File.dirname(File.expand_path($0)) # put path of this script on require path
require 'update_utils'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
   banner File.basename($0)
   opt :host, "phylodb database host", :required=>true, :type=>:string
   opt :dir, "flat file directory", :type=>:string, :required=>true
   opt :erase, "delete existing data for organism", :default=>true
end

db = Mysql.new(opts.host, "apis", "apis_user", "phylodb")

if File.exists?(opts.dir + "/" + "contigs.txt")
   if opts.erase
      File.new("contigs.txt").each do |line|
         ncbi, sp, strain, num, taxonomy,taxonomy, sg, form,
         seq, updated, type, ann = line.chomp.split("\t")
         deleteTaxonFromPhyloDB(db, num)
      end
   end
else
   STDERR << "contigs.txt not found!\n"
   exit(1)
end

["contigs", "geneorders", "proteins", "rrnas", "transcripts"].each do |table|
   txt = table + ".txt"
   if File.exists?(txt)
      cmd = "mysqlimport -h #{opts.host} -u apis --password=apis_user -L phylodb " + txt
      system(cmd)
   end
end
db.close
